import { ensureEnv } from '@take-out/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const BETTER_AUTH_SECRET = ensureEnv('BETTER_AUTH_SECRET')
export const BETTER_AUTH_URL = ensureEnv('BETTER_AUTH_URL')
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const VITE_PUBLIC_ZERO_SERVER = ensureEnv('VITE_PUBLIC_ZERO_SERVER', "")
export const ZERO_VERSION = ensureEnv('ZERO_VERSION', "")
// 🔒 end - this is generated by "bun env:update"

// database urls set conditionally based on deployment
// use bracket notation to prevent build-time inlining
export const ZERO_UPSTREAM_DB = process.env['ZERO_UPSTREAM_DB'] || ''
export const ZERO_CVR_DB = process.env['ZERO_CVR_DB'] || ''
export const ZERO_CHANGE_DB = process.env['ZERO_CHANGE_DB'] || ''
